### ISSUE TITLE
invalid_request - OAuth 2 parameters can only have a single value: grant_type

### ISSUE THREAD

**Issue by westhusing** [davido/gerrit-oauth-provider#64]
I've been unable to login to Gerrit with OAuth because I'm receiving the following error:

```
[2016-09-27 22:16:31,984] [HTTP-55] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?state=A2eIPFnldmHhWwlFDMU8aF2DBFqga5Gn8tx1vvYnIF4&code=4/NoyEEN7RUGjCleYTxglQzy7rof42ABwAfbJ5ZQNA5js
org.scribe.exceptions.OAuthException: Cannot extract an acces token. Response was: {
  "error" : "invalid_request",
  "error_description" : "OAuth 2 parameters can only have a single value: grant_type"
}
        at com.googlesource.gerrit.plugins.oauth.Google2Api$GoogleJsonTokenExtractor.extract(Google2Api.java:163)
        at com.googlesource.gerrit.plugins.oauth.Google2Api$GoogleOAuthService.getAccessToken(Google2Api.java:112)
        at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.getAccessToken(GoogleOAuthService.java:221)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:98)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:117)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:105)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

@davido, do you know what could be happening here?  Where should I dig deeper to find the root cause?

Thanks.

EDIT: This is Gerrit 2.12.5

**Comment by JmzTaylor** [comment]
Same scenario here.  Not sure when it started

**Comment by rtsai** [comment]
Also affected beginning today some time. Existing sessions are OK, but as people get expired and signed out, they are unable to sign back in.

Using gerrit-2.12.2 + gerrit-oauth-provider @ 56fbd4c28ba35877a38ec4c6bbfc6b5920db4207

**Comment by jpitt42** [comment]
I guess that answers my question.  I just finished posting https://github.com/davido/gerrit-oauth-provider/issues/66 before seeing this.  Me too with gerrit-2.12.4.

**Comment by rtsai** [comment]
Seems to be fixed with https://github.com/davido/gerrit-oauth-provider/pull/65

**Comment by westhusing** [comment]
Agreed, @rtsai.  I believe when PR #65 gets merged in, this issue will be resolved.

**Comment by luc-poynt** [comment]
applied the patch and 2.13.1 : still an issue
```
[2016-09-27 22:12:14,695] [HTTP-68] WARN  org.eclipse.jetty.servlet.ServletHandler : /r/oauth
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.gerrit.server.auth.oauth.OAuthTokenCache.put(OAuthTokenCache.java:80)
	at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:105)
	at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
	at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:77)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:122)
	at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:60)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:105)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

and (masked the token)
```
[2016-09-27 22:12:14,697] [HTTP-68] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /r/oauth?state=xxx&code=xxxx&authuser=0&hd=xxx&session_state=xxxx&prompt=none
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.gerrit.server.auth.oauth.OAuthTokenCache.put(OAuthTokenCache.java:80)
	at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:105)
	at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
	at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:77)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:122)
	at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:60)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:105)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

The values use for the token are correct ...

**Comment by rangaray** [comment]
I have same issue with below gerrit version. 

Gerrit Version : 2.10.2-18-gc6c5e0b-dirty
gerrit-oauth-provider : v2.10.2-18-gc6c5e0b

Please let me know fix for this issue.

Thanks

**Comment by davido** [comment]
@luc-poynt NPE is unrelated to this issue, see #63 and [pending efforts](https://gerrit-review.googlesource.com/#/c/87330) to fix it upstream for upcoming 2.13.2.

Fixed with #65.

**Comment by finik** [comment]
Thanks, David
Is the new binary release coming soon with the fix for this? My team is locked out of gerrit :)

I am trying to build myself but I follow the instructions and get this:
buck build plugin
No Android platform target specified. Using default: Google Inc.:Google APIs:23
[-] PROCESSING BUCK FILES...FINISHED 0.0s [100%]
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.3s [13%] (3/16 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
BUILD FAILED: android-4.4W in null is not a valid build tools directory.
Build tools directories should be follow the naming scheme: android-<VERSION>, build-tools-<VERSION>, or <VERSION>. Please remove directory android-4.4W.

Not sure how Android is related, never dealt with buck before
Thanks

**Comment by davido** [comment]
OK, will provide new release in a moment.

**Comment by davido** [comment]
@finik I'm not using Android, but I would really appreciate, if you could report your issue on [Buck Issue tracker](https://github.com/facebook/buck/issues), to track down your problem. Thanks.

**Comment by finik** [comment]
Done. Are you seeing the issue too? Should we wait for the release tonight?
Thanks!

**Comment by powderluv** [comment]
I see the same issue with 2.13.1. It locked out our engineers. The latest fix for #65 doesn't seem to fix it for me.

**Comment by finik** [comment]
@powderluv Where you find 2.13.1? I don't see it anywhere on the release page

**Comment by luc-poynt** [comment]
https://www.gerritcodereview.com/ the download on the right is for 2.13.1
we did more test and confirm that the patch works for 2.12.5 but now 2.13.1

**Comment by davido** [comment]
New release (including emergency fix for gerrit.war for those who upgraded to 2.13.x) is here: https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.13.1.

**Comment by TomaszKane** [comment]
Thanks!

**Comment by pslavov** [comment]
Hi,
Is it possible to compile with this patch for earlier gerrit version please. I am using gerrit 2.11.3 and it is not possible to upgrade right now.

**Comment by Jmennius** [comment]
@pslavov 
There is no need to do this, you should be able to use latest version with your 2.11 gerrit.

**Comment by jpitt42** [comment]
I built this patch off of tip-of-tree master last night and installed on our 2.12.4 Gerrit instance, but it had issues.  From the log, it was continuously loading and unloading the plugin.  I didn't spend any time debugging this.  I just reapplied the patch on top of https://github.com/davido/gerrit-oauth-provider/commit/e0134f44547a49d7e302247c12d11cf083c557ec, rebuilt, and it works fine.  Maybe the first attempt was an error on my side, because it sounds like it should have worked.

**Comment by pslavov** [comment]
@Jmennius - It worked for me - I didn't realize that this is possible.
Thanks for the help.

**Comment by ermshiperete** [comment]
:+1:  @davido Thanks for the quick fix.

The plugin from https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.13.1 worked on our 2.12.5 installation and we're able to login again.

**Comment by andi34** [comment]
Anyone knows if the latest plugin works on gerrit 2.11.1? Or updating gerrit too is a must?

**Comment by Jmennius** [comment]
@andi34 , 2.11 should work with latest plugin.

**Comment by tprochazka** [comment]
Did anyone with this quick fix installed tried to create new user account already?
There are no possibility to enter username name now.
See https://github.com/davido/gerrit-oauth-provider/issues/69#issuecomment-251889411
I'm not 100% sure that it is cause by plugin.

**Comment by westhusing** [comment]
Yes, I am running gerrit 2.13.1-10-gbf8b34a-dirty and I am having the same issue with new user accounts.  To set usernames, I had to manually update the gerrit database via gerrit gsql commands.

**Comment by powderluv** [comment]
@westhusing the official release doesn't work with Google OAuth unfortunately. 

The user name works with Github OAuth (it defaults to the github username automatically) but with Google OAuth it is empty.

**Comment by westhusing** [comment]
@powderluv Understood.

**Comment by tprochazka** [comment]
We solved it by update this oauth plugin configuration,  it was outdated
But I don't know exact details didn't do it.
